id: P84E49EAE
initial_creation_type: input
source_metadata:
  title: Mātṛcetra
  language: en
  description: 'Texts by and about Mātṛcetra (blo gros bkra):'
  volume:
    fc37f60a8786465f84335398f7db19d0:
      title: In Praise of the Three Jewels
      parent: Praise
created_at: '2022-03-01T02:17:21.048117'
last_modified_at: '2022-03-01T02:17:21.048123'
